#!/bin/bash
set -eu

# Resource Directories
export REPO_ROOT="$(pwd)/git"
export BUILD_ROOT="$(pwd)/build"
export CI_ROOT="$(pwd)/git-ci"
export VERSION_FROM="version/number"
export RELEASE_ROOT="${REPO_ROOT}/builds"

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${APP_NAME:-}"       || bail "APP_NAME must be set to the name of this package."

test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat "${VERSION_FROM}")
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

header "Building $APP_NAME v$VERSION..."

cd "$REPO_ROOT"
go version; echo; echo
make clean release-all VERSION="$VERSION" APP_NAME="$APP_NAME" RELEASE_ROOT="${RELEASE_ROOT}"
cd "$RELEASE_ROOT"
tar -zcvf "$BUILD_ROOT/$APP_NAME-$VERSION.tar.gz" "$APP_NAME-$VERSION-"*

echo
echo "================================================================================"
echo "SUCCESS!"
exit 0
