#!/bin/bash
set -eu

# Resource Directories
export REPO_ROOT="git"
export BUILD_ROOT="build"
export CI_ROOT="git-ci"
export VERSION_FROM="version/number"
export ROOT_PATH="$(pwd)"

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
test -n "${APP_NAME:-}"       || bail "APP_NAME must be set to the name of this package."

test -f "${VERSION_FROM}"     || bail "Version file (${VERSION_FROM}) not found."
VERSION=$(cat "${VERSION_FROM}")
test -n "${VERSION}"          || bail "Version file (${VERSION_FROM}) was empty."

OS=$(uname -s | tr A-Z a-z)
ARCH=$(uname -m | sed -e 's/^x86_/amd/')

[[ -e "$BUILD_ROOT/$APP_NAME-$VERSION-$OS-$ARCH" ]] || \
  bail "Cannot find app executable for v$VERSION on $OS/$ARCH"

header "Testing $APP_NAME v$VERSION ($OS/$ARCH)"

cd "$REPO_ROOT"
make test \
  TEST_PATH="../$CI_ROOT/ci/scripts/tests" \
  APP_PATH="../$BUILD_ROOT/$APP_NAME-$VERSION-$OS-$ARCH"

#TODO: Build a credhub setup, connect using the app in ../build/, validate
#      function
echo
echo "================================================================================"
echo "SUCCESS!"
exit 0

