---
meta:
  name:    vault-credhub-proxy
  release: Vault Credhub Proxy
  target:  pipes/cloudfoundry-community
  url:     https://pipes.scalecf.net

  initial_version: 0.0.5

  go:
    force_static_binary: true

  git:
    email:           ci@cloudfoundry-community.com
    name:            Cloudfoundry Community CI Bot

  aws:
    access_key:      ((aws.access_key_id))
    secret_key:      ((aws.secret_access_key))

  github:
    owner:           cloudfoundry-community
    repo:            vault-credhub-proxy
    branch:          develop
    main-branch:     main
    private_key:     ((github.private_key))
    access_token:    ((github.access_token))
    access_token_rw: ((github.access_token_rw))

  slack:
    webhook:         ((slack.webhook))
