---
meta:
  name:    vault-credhub-proxy
  target:  pipes/cloudfoundry-community
  url:     https://pipes.scalecf.net

  git:
    name:  Cloudfoundry Community CI Bot
    email: ci@loudfoundry-community.org

  github:
    owner: cloudfoundry-community
    repo:  vault-credhub-proxy
    branch: develop
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  slack:
    webhook: ((slack.webhook))
    channel: "#nochannel"
