jobs:
- name: rc
  public: true
  plan:
  - in_parallel:
      - { get: git,     trigger: true,  passed: [pre] }
      - { get: version, trigger: false, params: {pre: rc} }
  - put: version
    params: {file: version/number}
  # on_failure:
  #   put: notify
  #   params:
  #     channel:  (( grab meta.slack.channel ))
  #     username: (( grab meta.slack.username ))
  #     icon_url: (( grab meta.slack.icon ))
  #     text:    '(( concat meta.slack.fail_url " " meta.pipeline ": rc job failed" ))'
