jobs:
  - name: test
    public: true
    serial: false
    plan:
    - in_parallel: 
        steps: 
        - { get: build,   passed: [build], trigger: true, params: {unpack: true}}
        - { get: version, passed: [build]}
        - { get: git,     passed: [build]}
        - { get: git-ci}
    - load_var: vault_version
      file: github-vault-1.10/version
      format: trim
      reveal: true
    - task: test
      file: git-ci/ci/tasks/test.yml
      params:
        APP_NAME: (( grab meta.name ))
    on_failure:
      put: notify
      params:
        username: (( grab meta.slack.username ))
        icon_url: (( grab meta.slack.icon ))
        text:    '(( concat meta.slack.fail_url " " meta.pipeline ": test job failed" ))'

